logger:
  level: info

db:
  type: sql
  sql:
    driver: pgx
    name: calendar
    user: postgres
    password: postgres
    host: postgres
    port: 5432

rmq:
  host: rabbitmq
  port: 5672
  user: guest
  pswd: guest

queuename: "sender"
