logger:
  level: "info"

server:
  host: 127.0.0.1
  port: 2014

grpcserver:
  host: 127.0.0.1
  port: 2022

db:
  type: "sql"
  sql:
    driver: "pgx"
    name: "calendar"
    user: "postgres"
    password: "postgres"
    host: "localhost"
    port: "5432"
