logger:
  level: "info"

db:
  type: "sql"
  sql:
    driver: "pgx"
    name: "calendar"
    user: "postgres"
    password: "postgres"
    host: "localhost"
    port: "5432"

rmq:
  host: 127.0.0.1
  port: 5672
  user: guest
  pswd: guest

queuename: "sender"
